travis:
  secure:
    BINSTAR_TOKEN: Px3fFhqScsNOamjnncNY6srGelTWYwZM4vkQp6tFFH+vdQDD2xMjOSM6QrerPKLCz1z4l4RZqIgIBYMDQoHazSrZ26Fmu/L7ggXSuwVqnHhzDtBrdDd98Zi8m6A+yb6IN/1GKKL8j+FKnV/9S3c4koZQ75aVDwSjcPU8vYD5a8Cr5Hfdp9mKXfglaFPdpbE5N1M1XsDGdh/TjE+TeIQBl4Cf9weVG2zI9JDFmaB+co/dOIhdaWGbgdWE4JCAICA3iyL+1LdEKJSWFRupPDyFhCnmu+Iljdj1GBzVoSGURlANQ3isApyUOxHUH5CJ7CPJjhTXRx5pf7SFqSMjLgtMgZk0nHS9dq0dZD085fvXcLtQjEGBZsQkxS6s6KAXKaxGlGkLVNJtWndEycLoCWd969umiAbRDpzUBYdRHzGg15gRq+nWZadgZfEVFZMI6JQo2SZx/rznohVe1RVLi/Az4q/vdEFrEBm4kKHXL8QiQapJWUkYsXdTX0ExrQjo5GdXWEKrCBPmyX3TLzU08ICtnJSKXkG+Ok7MKbH9ndhkxuc6B+95pkhBi96e+uWOZQVr4xEjBx3GUkRaEIOgtyjUjHDHYifeo08bnz7e1MnZ1XTPPxH4eey5olw+ruWIlYYMFcaepgzjT12R2XeelyBIVbLxWlxReyv6oanpBqY8bSc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
